# Probabilities Is All You Need
## Chasing Determinism across Classical ML, Supervised NLP, and Low-Rank Adapted Foundation Models

*Simon Reichel*

---
## TOC
1. Environment info
2. [only in deterministic notebook]
3. [only in deterministic notebook]
4. Config class
5. Define `set_determinism()` function
6. Training dataset pre-processing
7. Inference dataset pre-processing
8. Model training \
8.1 Logistic regression \
8.2 Fine-tune encoder-transformer \
8.3 Low Rank Adaptation (LoRA) on foundation model
9. Model inference \
9.1 Logistic regression \
9.2 Encoder-transformer \
9.3 Foundation model \
9.4 [only in deterministic notebook]
10. [only in deterministic notebook]

---
## 1 Environment info

**Distro:** Linux Fedora 43 for Workstation \
**Kernel:** Linux 7.0.12-101.fc43.x86_64 \
**NVIDIA CUDA:** v13.2 \
**NVIDIA driver:** v580.159.04 \
**GPU:** NVIDIA Blackwell GB203 \
**CPU:** Intel 12th Gen Core i5-12600K / 16 logical cores @ 4.90 GHz \
**DRAM:** 64 Gigabytes (~62.8 Gibibyte) at JEDEC-3200-16-20-20-38 1.35V, manufactured by Micron \
**Mass storage:** 1 Terabyte (~928.9 Gibibyte) SAMSUNG 870QVO SATA-III-600

Reporting hardware and driver versions matters for reproducibility: cuDNN (= CUDA Deep Neural Networks) and cuBLAS (= CUDA Basic Linear Algebra Subprograms) select different low-level kernels depending on GPU architecture, driver version, and CUDA toolkit version, and these kernels are not guaranteed to be bit-identical across configurations even with identical seeds and deterministic flags.

---
## 4 Config class

We define a `Config` dataclass that holds every important parameter as a single source of truth, which makes parameters easy to control and change in one place. \
We treat `Config` as a module. This way we can import it into both notebooks and ensure all paramteres are identical for both notebooks.

> **Note:** we use `@dataclass` rather than a plain class specifically because dataclasses auto-generate `__init__`/`__repr__`/`__eq__`, and, importantly for mutable defaults like `list`, require `field(default_factory=...)` instead of a bare mutable default. A bare `list` or `dict` default on a plain class attribute would be *shared* across all instances of that class, which can lead to state-leakage bugs. We likely never instantiate `Config` more than once here, but avoiding shared mutable state is good practice regardless.

As `seed` we choose **12011853**, the birth date of Gregorio Ricci-Curbastro (12 January 1853), in honour of his foundational work on tensor calculus (the *Ricci calculus*), which underlies much of the linear-algebraic machinery used throughout modern machine learning.

In [1]:
from pathlib import Path # needed later

# import custom Config class
from Config import cfg

# sepcify non-determinism
cfg.deterministic = False

We can already specify our CUDA device as a `torch` device for later use, and take the opportunity to sanity-check the installed CUDA/PyTorch versions against what this notebook was developed against.

In [2]:
import torch

# specify torch device
device = torch.device(cfg.device)

# sanity-check the installed versions against the ones this notebook was developed with
print(f"CUDA version: {torch.version.cuda} (developed against: 13.2)")
print(f"torch version: {torch.__version__} (developed against: 2.13.0)")

CUDA version: 13.2 (developed against: 13.2)
torch version: 2.13.0+cu132 (developed against: 2.13.0)

---
## 5 Define `set_determinism()` function

We define `set_determinism()`, a function that configures every seed and every determinism-relevant flag we have programmatic control over. Even with this function applied, a small amount of non-determinism remains: OS-level thread/kernel scheduling and certain GPU reduction kernels are inherently non-deterministic and are out of reach from user-space Python.

\
`set_determinism()` sets the following, when `cfg.deterministic is True`:

- **`torch.manual_seed(seed)`** seeds PyTorch's CPU (and, as a side effect, default CUDA) random number generator. Not every PyTorch operation consumes randomness from this generator, which is why several more seeds are needed below.
  
- **`torch.cuda.manual_seed_all(seed)`** seeds the CUDA RNG on *all* visible GPUs (the `_all` suffix matters in multi-GPU settings; the non-suffixed variant only seeds the current device).

- **`np.random.seed(seed)`** seeds NumPy's legacy global RNG, which many libraries (including parts of scikit-learn) depend on internally.

- **`random.seed(seed)`** seeds Python's standard-library `random` module, used implicitly by some libraries without this being obvious from their public API.

- **`torch.use_deterministic_algorithms(True, warn_only=True)`** instructs PyTorch to prefer deterministic kernel implementations wherever they exist. Some operations (e.g. certain scatter/gather patterns, some CUDA reduction kernels) have no deterministic implementation at all. With `warn_only=True`, PyTorch falls back to the non-deterministic implementation and emits a warning instead of raising `RuntimeError`; with `warn_only=False` it would raise instead.

- **`torch.utils.deterministic.fill_uninitialized_memory = True`** is a *property assignment*, not a function call - this is a small but easy mistake to make (an earlier version of this code incorrectly attempted `fill_uninitialized_memory(True)`, treating it like `torch.use_deterministic_algorithms()`). When set, newly allocated tensors that PyTorch would otherwise leave with arbitrary uninitialized memory (e.g. from `torch.empty`) are instead deterministically zero-filled. Left at its default, the *contents* of such tensors are undefined and can vary between runs - not because anything is being computed non-deterministically, but because the memory simply was never written.

- **`torch.backends.cudnn.deterministic = True`** forces cuDNN to use only its deterministic convolution/pooling algorithm implementations. (An earlier version of this notebook stated this flag as `= False` while describing the deterministic behaviour - that was a copy-paste error in the markdown, not in the code; the code cell below has always used `= True` in the deterministic branch.)

- **`torch.backends.cudnn.benchmark = False`** disables cuDNN's autotuning heuristic, which would otherwise time several candidate algorithms on the first forward pass and cache whichever is fastest - a choice that can itself depend on non-deterministic timing and on input shapes seen so far. Disabling it makes cuDNN pick algorithms deterministically based on the operation's static parameters instead.

- **`generator = torch.Generator().manual_seed(seed)`** creates a seeded generator object intended for PyTorch `DataLoader`. Setting the global seeds above is not sufficient for `DataLoader` workers: when `num_workers > 0`, each worker process is forked and reseeded independently, so **this `generator` object must be passed explicitly** as `DataLoader(..., generator=generator, worker_init_fn=seed_worker)` for worker-level reproducibility - the seeds set above do not propagate into worker processes on their own. We return `generator` from this function precisely so it can be threaded through to any `DataLoader` used later (Tasks 2 and 3).

When `cfg.deterministic is False`, the mirrored branch draws a fresh pseudo-random seed via `random.SystemRandom()` and disables all of the above, additionally re-enabling `cudnn.benchmark` so that cuDNN is free to autotune for speed.

In [3]:
import numpy as np
import random

def set_determinism(cfg):

    if cfg.deterministic is True:

        # take seed from Config
        seed = cfg.seed

        # torch seed fixed
        torch.manual_seed(seed)

        # NVIDIA CUDA seed fixed (all visible devices)
        torch.cuda.manual_seed_all(seed)

        # numpy seed fixed
        # numpy is a dependency in many modules
        np.random.seed(seed)

        # random seed fixed
        # some functions might use this without specifically saying so
        random.seed(seed)

        # prefer deterministic algorithms where they exist
        # explicitly fore determinism by warn_only = False
        torch.use_deterministic_algorithms(True,
                                           warn_only = False)

        # force newly allocated tensors to be zero-filled rather than left
        # with arbitrary uninitialized memory contents
        torch.utils.deterministic.fill_uninitialized_memory = True

        # restrict NVIDIA cuDNN to deterministic algorithm implementations
        torch.backends.cudnn.deterministic = True

        # disable cuDNN's autotuning benchmark so algorithm choice is static,
        # not the (non-deterministic) fastest-of-several-timed-runs
        torch.backends.cudnn.benchmark = False

        # seeded generator for DataLoader workers - must be passed explicitly
        # to DataLoader(..., generator=generator, worker_init_fn=seed_worker)
        generator = torch.Generator().manual_seed(seed)

    else:
        # choose a pseudo-random 32-bit integer
        seed = random.SystemRandom().randint(0, 2**31 - 1)

        # torch seed
        torch.manual_seed(seed)

        # NVIDIA CUDA seed
        torch.cuda.manual_seed_all(seed)

        # numpy seed
        np.random.seed(seed)

        # random seed
        # some functions might use this without specifically saying so
        random.seed(seed)

        # allow torch to fall back to non-deterministic (typically faster) algorithms
        torch.use_deterministic_algorithms(False)

        # tensors may contain arbitrary uninitialized (non-deterministic) values
        torch.utils.deterministic.fill_uninitialized_memory = False

        # allow cuDNN to select non-deterministic algorithms
        torch.backends.cudnn.deterministic = False

        # let cuDNN autotune and cache the fastest algorithm per input shape
        torch.backends.cudnn.benchmark = True

        # generator still seeded, just not reproducible across runs
        generator = torch.Generator().manual_seed(seed)

    print(f"Operations are near-deterministic: {cfg.deterministic}")
    print(f"Seed: {seed}")

    return seed, generator

---
## 6 Training dataset pre-processing

For training we use the SB10k dataset for three-class sentiment analysis by Cieliebak et al. (2017). \
The dataset already has train and test splits.

In [4]:
import pandas as pd

# read datasets
train_split = pd.read_table(cfg.sb10k_train,
                            usecols = [1, 2],
                            names = ["rating", "text"]) # specify column headers

test_split = pd.read_table(cfg.sb10k_test,
                            usecols = [1, 2],
                            names = ["rating", "text"]) # specify column headers


print(f"Rows train_split: {len(train_split)}")
print(f"Rows test_split: {len(test_split)}")
print(f"Split ratio: {len(test_split) / len(train_split)}")
train_split.head()

Rows train_split: 5233
Rows test_split: 1496
Split ratio: 0.285878081406459

     rating                                               text
0  positive  RT @TheKedosZone : So ein Hearthstone - Key vo...
1   neutral  Tainted Talents ( Ateliertagebuch. ) " Wir sin...
2   neutral  Aber wenigstens kommt #Supernatural heute mal ...
3   neutral  DARLEHEN - Angebot für Schufa - freie Darlehen...
4   neutral  ANRUF ERWÜNSCHT : Hardcore Teeny Vicky Carrera...

Per convention, our split names are:
- `X_train`: strings for training
- `X_eval`: strings for validation
- `y_train`: labels for training
- `y_eval`: labels for validation
- `X_test`: Texts for human annotated labels for final quality control
- `y_test`: Human annotated labels for final quality control

In [5]:
# transform splits
X_train = train_split["text"]
X_eval = test_split["text"]

y_train = train_split["rating"]
y_eval = test_split["rating"]

# look at distributions
print(f"Train split class distributions: {y_train.value_counts()}")
print(f"Test split class distributions: {y_eval.value_counts()}")

Train split class distributions: rating
neutral     3246
positive    1193
negative     794
Name: count, dtype: int64
Test split class distributions: rating
neutral     930
positive    354
negative    212
Name: count, dtype: int64

---
## 7 Inference dataset pre-processing

In [6]:
# read data
dataset_inference = pd.read_csv(cfg.dataset_path)

# verify
dataset_inference.info()

<class 'pandas.DataFrame'>
RangeIndex: 8627 entries, 0 to 8626
Columns: 151 entries, StartDate to analysis_summary
dtypes: bool(1), float64(69), int64(3), object(2), str(76)
memory usage: 30.7+ MB

/tmp/ipykernel_10120/1830462024.py:2: DtypeWarning: Columns (0: Q91_2_TEXT, 1: eval_compassionate, 2: q42_2, 3: q20_10_TEXT, 4: q22_10_TEXT, 5: q75_10_TEXT, 6: PROLIFIC_PID, 7: stereoRecordingUrl) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_inference = pd.read_csv(cfg.dataset_path)

In [7]:
# drop unnecessary columns
dataset_reduced = dataset_inference[cfg.dataset_columns]

# verify
dataset_reduced.head()

,interviewId,messageId,role,message
0,afaf2cf9-66c3-44e6-b183-44f704e8278b,afaf2cf9-66c3-44e6-b183-44f704e8278b_msg_001,system,# Rolle\n\nSie sind ein kompetenter Interviewe...
1,afaf2cf9-66c3-44e6-b183-44f704e8278b,afaf2cf9-66c3-44e6-b183-44f704e8278b_msg_002,bot,"Hallo, Ich freue mich, heute mit Ihnen spreche..."
2,afaf2cf9-66c3-44e6-b183-44f704e8278b,afaf2cf9-66c3-44e6-b183-44f704e8278b_msg_003,user,"Er Ja, wir können starten."
3,afaf2cf9-66c3-44e6-b183-44f704e8278b,afaf2cf9-66c3-44e6-b183-44f704e8278b_msg_004,bot,"Herzlich willkommen und vielen Dank, dass Sie ..."
4,afaf2cf9-66c3-44e6-b183-44f704e8278b,afaf2cf9-66c3-44e6-b183-44f704e8278b_msg_005,user,Ich möchte direkt loslegen.

We are only interested in user messages, since these already constitute natural-language entities on their own (as opposed to system prompts or structured assistant replies). \
We additionally drop messages with fewer than `cfg.min_words` words, since very short replies rarely carry enough content to be judged reliably for sentiment - note that this is a **word-count** threshold (`str.split().str.len()` counts whitespace-separated tokens), not a character-length threshold.

We then draw a pseudo-random sample for manual annotation, which will later serve as real-world validation data across all three architectures.

In [8]:
# select only user messages
dataset_user = dataset_reduced[dataset_reduced["role"] == "user"]

# keep only messages with at least cfg.min_words words
dataset_user = dataset_user[dataset_user["message"].str.split().str.len() >= cfg.min_words]

# check dataset size
print(f"Remaining messages: {len(dataset_user)}")

# pull pseudo-random sample
dataset_annotations = dataset_user.sample(n = cfg.sample_size,
                                          random_state = cfg.seed
                                         )

# check annotation dataset size
print(f"Annotation dataset size: {len(dataset_annotations)}")

Remaining messages: 2376
Annotation dataset size: 100

In [9]:
# export to .csv
dataset_annotations.to_csv(cfg.output_path,
                           encoding = "UTF-8",
                           index = False,
                           sep = "|"  # unlikely to appear in the data
                          )

In [10]:
# read in annotated gold standard
annotations = pd.read_csv(cfg.annotations_path,
                         encoding = "UTF-8",
                         sep = "|")
# verify
annotations.head()

,interviewId,messageId,role,message,annotation
0,0199acb4-fa0f-7aa1-832b-434f16efabec,0199acb4-fa0f-7aa1-832b-434f16efabec_msg_013,user,"Also ich weiß nicht, was das für eine woher di...",negative
1,019a166f-087d-744b-8d35-9210ba214452,019a166f-087d-744b-8d35-9210ba214452_msg_013,user,"Ja, es ist so wie weil ich will in eine sicher...",negative
2,0199f21f-de76-7005-9463-82a657ba3bf9,0199f21f-de76-7005-9463-82a657ba3bf9_msg_011,user,"Es sind die Gespräche mit Menschen, die man fü...",negative
3,019a0bc7-1ca6-7ff7-823e-773cf5502d21,019a0bc7-1ca6-7ff7-823e-773cf5502d21_msg_021,user,"Weil es ihnen hier zu gut geht, weil wir sie z...",negative
4,019a0895-200f-766d-82ba-62335fdc710a,019a0895-200f-766d-82ba-62335fdc710a_msg_011,user,Die Leute sind nicht dafür qualifiziert. Und w...,negative

In [11]:
# create test split
X_test = annotations["message"] # not the same as X_eval!
y_test = annotations["annotation"] # not the same as y_eval!

---
## 8 Model training

We train on three different architectures. First, we are training from scratch on a logistic regression classifier. Afterwards we are applying transfer learning on a BERT-like transformer. Finally, we apply transfer learning on a small Large Language Model. \
We purposefully do not conduct k-fold cross validation to ensure all models within each architecture are trained on the exact same data, eliminating a source of noise. \
\
To evaluate differences in training and inference due to non-deterministic or near-deterministic environments, we train ten models for each architecture and inference over the dataset 20 times for each model. \
Therefore, we will inference the dataset a total of 1200 times (60 models with 20 runs each), giving us a broad basis for comparisons.

Before running any of the three tasks, we will call `set_determinism()`. Most of its effects are irrelevant to logistic regression (there is no cuDNN, no CUDA tensor allocation, no `DataLoader`). However, they become relevant starting with Task 2, which uses a GPU-resident transformer encoder.

### 8.1 Logistic regression

We use `nltk` to remove German stopwords:

In [12]:
import json
import joblib
import sklearn
import platform
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score, 
    precision_recall_fscore_support,
    classification_report, 
    confusion_matrix
)
import nltk
from nltk.corpus import stopwords
from time import perf_counter
from datetime import datetime


# download German stopwords
nltk.download("stopwords")

german_stopwords = stopwords.words("german")

# add to Config params
cfg.tfidf_params["stop_words"] = german_stopwords

[nltk_data] Downloading package stopwords to /home/simon/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Because we want to train the model multiple times, we define a set of functions. \
We define a pipeline, an evaluation function for the most important metrics and a `fit_and_save` function which will fit the model and then save it to our storage.

In [13]:
# define logistic regression pipeline
def build_pipeline(tfidf_params = None, 
                   clf_params = None):
    
    tfidf_params = tfidf_params or {}
    clf_params = clf_params or {}
    
    return Pipeline([
        ("tfidf", TfidfVectorizer(**tfidf_params)),
        ("clf", LogisticRegression(**clf_params)),
    ])

In [14]:
# define evaluation function
def evaluate(pipeline, 
             X_test, 
             y_test):
    
    y_pred = pipeline.predict(X_test)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_test, y_pred, average = "macro", zero_division = 0
    )
    
    return {
        "accuracy": accuracy_score(y_test, y_pred),
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "classification_report": classification_report(
            y_test, y_pred, output_dict = True, zero_division = 0
        ),
        "confusion_matrix": confusion_matrix(y_test, y_pred).tolist(),
    }

In [15]:
# define fitting model and saving to storage
def fit_and_save(name, 
                 tfidf_params, 
                 clf_params, 
                 X_train, 
                 y_train, 
                 X_test, 
                 y_test):
    
    pipeline = build_pipeline(tfidf_params, 
                              clf_params)

    start = perf_counter()
    pipeline.fit(X_train, y_train)
    fit_seconds = perf_counter() - start

    metrics = evaluate(pipeline, 
                       X_test, 
                       y_test)

    # save model
    model_path = Path(cfg.output_directory_logistic_nondeterministic) / f"{name}.joblib"
    joblib.dump(pipeline, model_path)

    # save metadata for later documentation / paper
    metadata = {
        "name": name,
        "timestamp": datetime.now().isoformat(),
        "tfidf_params": tfidf_params,
        "clf_params": clf_params,
        "fit_seconds": fit_seconds,
        "n_train": len(X_train),
        "n_test": len(X_test),
        "metrics": metrics,
        "model_path": str(model_path),

        # versions
        "scikit learn version": sklearn.__version__, 
        "Python version": platform.python_version()
    }
    
    metadata_path = Path(cfg.output_directory_logistic_nondeterministic) / f"{name}_metadata.json"
    with open(metadata_path, "w") as f:
        json.dump(metadata, f, indent = 2)

    print(f"[{name}] acc = {metrics['accuracy']:.4f}  f1 = {metrics['f1']:.4f} fitted in {fit_seconds:.2f} seconds and was saved to {model_path}")

    return pipeline, metadata

We can now run training.

In [19]:
results_logistic = {}

# fit ten models
for x in range(cfg.n_models):

    # set each time
    seed, generator = set_determinism(cfg)

    #drop pipeline with _
    _, meta = fit_and_save(cfg.name_prefix_logistic_nondeterministic + str(x),
                           cfg.tfidf_params,
                           cfg.clf_params,
                           X_train,
                           y_train,
                           X_test,
                           y_test
                          )
    results_logistic[x] = meta

with open(Path(cfg.output_directory_logistic_nondeterministic) / "summary_nondeterministic.json", "w") as f:
    json.dump(
        {k: {"accuracy": v["metrics"]["accuracy"],
             "recall": v["metrics"]["recall"],
             "precision": v["metrics"]["precision"],
             "f1": v["metrics"]["f1"]}
         for k, v in results_logistic.items()},
        f, 
        indent = 2
    )

Operations are near-deterministic: False
Seed: 567488680
[logistic_regression_nondeterministic_0] acc = 0.4800  f1 = 0.3336 fitted in 4.20 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Logistic Regression Models Non-Deterministic/logistic_regression_nondeterministic_0.joblib
Operations are near-deterministic: False
Seed: 1849087961
[logistic_regression_nondeterministic_1] acc = 0.4800  f1 = 0.3336 fitted in 4.08 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Logistic Regression Models Non-Deterministic/logistic_regression_nondeterministic_1.joblib
Operations are near-deterministic: False
Seed: 1318221941
[logistic_regression_nondeterministic_2] acc = 0.4800  f1 = 0.3336 fitted in 4.22 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Logistic Regression Models Non-Deterministic/logistic_regression_nondeterministic_2.joblib
Operations are near-deterministic: False
Seed: 215253707
[logistic_regression_nondeterministic_3] acc = 0.4800  f1 = 0.3336 fitted in 4.24 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Logistic Regression Models Non-Deterministic/logistic_regression_nondeterministic_3.joblib
Operations are near-deterministic: False
Seed: 1063295305
[logistic_regression_nondeterministic_4] acc = 0.4800  f1 = 0.3336 fitted in 4.16 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Logistic Regression Models Non-Deterministic/logistic_regression_nondeterministic_4.joblib
Operations are near-deterministic: False
Seed: 120782835
[logistic_regression_nondeterministic_5] acc = 0.4800  f1 = 0.3336 fitted in 3.97 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Logistic Regression Models Non-Deterministic/logistic_regression_nondeterministic_5.joblib
Operations are near-deterministic: False
Seed: 1278457723
[logistic_regression_nondeterministic_6] acc = 0.4800  f1 = 0.3336 fitted in 4.07 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Logistic Regression Models Non-Deterministic/logistic_regression_nondeterministic_6.joblib
Operations are near-deterministic: False
Seed: 1993807201
[logistic_regression_nondeterministic_7] acc = 0.4800  f1 = 0.3336 fitted in 4.12 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Logistic Regression Models Non-Deterministic/logistic_regression_nondeterministic_7.joblib
Operations are near-deterministic: False
Seed: 1427082250
[logistic_regression_nondeterministic_8] acc = 0.4800  f1 = 0.3336 fitted in 4.07 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Logistic Regression Models Non-Deterministic/logistic_regression_nondeterministic_8.joblib
Operations are near-deterministic: False
Seed: 1336020792
[logistic_regression_nondeterministic_9] acc = 0.4800  f1 = 0.3336 fitted in 4.21 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Logistic Regression Models Non-Deterministic/logistic_regression_nondeterministic_9.joblib

### 8.2 Encoder Transformer

In [13]:
import numpy as np
import accelerate
from datasets import Dataset
from torch.utils.data import DataLoader
import accelerate.utils
import transformers as tf

/home/simon/anaconda3/envs/ml_non-determinism/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

We define a `get_metrics` function which does essentially the same as the `evaluate` function we defined for logistic regression.

In [14]:
def get_metrics(eval_pred):
    
    logits, labels = eval_pred
    preds = np.argmax(logits, axis = -1)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, 
        preds, 
        average = "macro", 
        zero_division = 0
    )
    
    return {
        "accuracy": accuracy_score(labels, preds),
        "precision": precision,
        "recall": recall,
        "f1": f1,
    }

Define the training loop and checkpoint logging:

In [15]:
def fit_and_save_transformer(cfg,
                             name,
                             X_train_input, 
                             y_train_input,
                             X_eval_input, 
                             y_eval_input, 
                             X_test_input = None, 
                             y_test_input = None):
    
    tf.set_seed(seed)  # seed for reproducibility

    # set output directory
    run_dir = Path(cfg.output_directory_encoder_nondeterministic) / name
    # verify it exists
    run_dir.mkdir(parents = True, exist_ok = True)
    
    tokenizer = tf.AutoTokenizer.from_pretrained(cfg.model_checkpoint)
    model = tf.AutoModelForSequenceClassification.from_pretrained(
        cfg.model_checkpoint, 
        num_labels = cfg.num_labels # number of classes
    )

    def tokenize(batch):
        
        return tokenizer(batch["text"], 
                         truncation = True, 
                         padding = "max_length",
                         max_length = cfg.max_length)

    #convert splits to list for trainer
    train_texts = X_train_input.reset_index(drop = True).tolist()
    train_labels = y_train_input.reset_index(drop = True).tolist()
    eval_texts = X_eval_input.reset_index(drop = True).tolist()
    eval_labels = y_eval_input.reset_index(drop = True).tolist()
    
    if X_test_input is not None:
        test_texts = X_test_input.reset_index(drop = True).tolist()
        test_labels = y_test_input.reset_index(drop = True).tolist()
    
    train_ds = Dataset.from_dict({"text": train_texts, "label": train_labels}).map(
        tokenize, batched = True
    )
    eval_ds = Dataset.from_dict({"text": eval_texts, "label": eval_labels}).map(
        tokenize, batched = True
    )

    training_args = tf.TrainingArguments(
        output_dir = str(run_dir / "checkpoints"),
        learning_rate = cfg.learning_rate,
        per_device_train_batch_size = cfg.batch_size,
        per_device_eval_batch_size = cfg.batch_size,
        num_train_epochs = cfg.num_epochs,
        weight_decay = cfg.weight_decay,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        save_total_limit = 2, # keep only last 2 checkpoints to save memory
        load_best_model_at_end = True,
        metric_for_best_model = "f1",
        seed = seed,
        data_seed = seed,
        report_to = "none",
        logging_dir = str(run_dir / "logs"), # deprecated but we would have to set it as an env variable instead -> not going to do that
        bf16 = cfg.use_bf16, # mixed precision on Blackwell
        tf32 = cfg.use_tf32, # speed up fp32 matmuls on Blackwell
        dataloader_pin_memory = True
    )

    # use trainer
    trainer = tf.Trainer(
            model = model,
            args = training_args,
            train_dataset = train_ds,
            eval_dataset = eval_ds,
            compute_metrics = get_metrics,
            callbacks = [tf.EarlyStoppingCallback(early_stopping_patience = cfg.patience)]
        )

    start = perf_counter()
    trainer.train()
    fit_seconds = perf_counter() - start

    eval_metrics = trainer.evaluate()

    # Save the final best model
    final_dir = run_dir / "final_model"
    trainer.save_model(str(final_dir))
    tokenizer.save_pretrained(str(final_dir))

    # Use annotated gold-standard
    test_metrics = None
    if test_texts is not None:
        test_ds = Dataset.from_dict({"text": test_texts, "label": test_labels}).map(
            tokenize, batched = True
        )
        
        preds_output = trainer.predict(test_ds)
        preds = np.argmax(preds_output.predictions, axis = -1)
        precision, recall, f1, _ = precision_recall_fscore_support(
            test_labels, 
            preds, 
            average = "macro", 
            zero_division = 0
        )

        # will only be created if test_texts exist
        test_metrics = {
            "accuracy": accuracy_score(test_labels, preds),
            "precision": precision,
            "recall_": recall,
            "f1": f1,
            "confusion_matrix": confusion_matrix(test_labels, preds).tolist(),
        }

    
    metadata = {
        "name": name,
        "timestamp": datetime.now().isoformat(),
        "model_checkpoint": cfg.model_checkpoint,
        "hyperparameters": {
            "learning_rate": cfg.learning_rate,
            "batch_size": cfg.batch_size,
            "num_epochs": cfg.num_epochs,
            "weight_decay": cfg.weight_decay,
            "max_length": cfg.max_length,
        },
        "fit_seconds": fit_seconds,
        "eval_metrics": eval_metrics,
        "test_metrics": test_metrics,
        "final_model_path": str(final_dir),
        "CUDA_device_memory_used": torch.cuda.memory_reserved(0), # get info about needed GPU memory
        "torch_version": torch.__version__,
    }

    # save metadata as json
    with open(run_dir / "metadata.json", "w") as f:
        json.dump(metadata, 
                  f, 
                  indent = 2)

    print(f"[{name}] eval_f1={eval_metrics.get('eval_f1', 'NA')} fitted in {fit_seconds:.2f} seconds and was saved to {final_dir}")

    return trainer, metadata

Before we can run inference, we need to change our labels from strings to integers. Otherwise `torch` will not be able to convert them into a tensor.

In [16]:
y_train_int = y_train.replace(
    ["negative",
    "neutral",
    "positive"],
    [0,
    1,
    2]
)

y_eval_int = y_eval.replace(
    ["negative",
    "neutral",
    "positive"],
    [0,
    1,
    2]
)

y_test_int = y_test.replace(
    ["negative",
    "neutral",
    "positive"],
    [0,
    1,
    2]
)

In [18]:
results_encoder = {}

# fit ten models
for x in range(cfg.n_models):

    # set each time
    seed, generator = set_determinism(cfg)
    
    _, meta = fit_and_save_transformer(
        cfg,
        cfg.name_prefix_encoder_nondeterministic + str(x),
        X_train, 
        y_train_int, # labels converted to integers
        X_eval, 
        y_eval_int, # labels converted to integers
        X_test, 
        y_test_int # labels converted to integers      
    )

    results_encoder[x] = meta

    #free up GPU memory between runs
    del _
    torch.cuda.empty_cache()

summary = {
    name: {
        "eval_f1": meta["eval_metrics"].get("eval_f1"),
        "test_f1": (meta["test_metrics"] or {}).get("f1"),
        "fit_seconds": meta["fit_seconds"],
    }
    
    for name, meta in results_encoder.items()
}

with open(Path(cfg.output_directory_encoder_nondeterministic) / f"summary_nondeterministic.json", "w") as f:
    json.dump(summary,
              f,
              indent = 2)

#free up GPU memory at the end
torch.cuda.empty_cache()

Operations are near-deterministic: False
Seed: 911191029

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 15976.01it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-german-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5233/5233 [00:00<00:00, 36299.04 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1496/1496 [00:00<00:00, 26339.96 examples/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.52it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.01it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.52it/s]

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.26s/it]
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 12325.31 examples/s]

[BERT-Base-German_0] eval_f1=0.682338517625268 fitted in 36.40 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/BERT Transformer Models Non-Deterministic/BERT-Base-German_0/final_model
Operations are near-deterministic: False
Seed: 1063775900

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 20777.32it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-german-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5233/5233 [00:00<00:00, 34421.49 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1496/1496 [00:00<00:00, 27787.43 examples/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.51it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.02it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.32it/s]

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 12943.39 examples/s]

[BERT-Base-German_1] eval_f1=0.6799469129793657 fitted in 36.63 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/BERT Transformer Models Non-Deterministic/BERT-Base-German_1/final_model
Operations are near-deterministic: False
Seed: 1441641906

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 12699.38it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-german-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5233/5233 [00:00<00:00, 28366.63 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1496/1496 [00:00<00:00, 24620.00 examples/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.47it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.63it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.93it/s]

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.42s/it]
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 12004.65 examples/s]

[BERT-Base-German_2] eval_f1=0.666259215588134 fitted in 36.24 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/BERT Transformer Models Non-Deterministic/BERT-Base-German_2/final_model
Operations are near-deterministic: False
Seed: 720427480

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 15314.42it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-german-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5233/5233 [00:00<00:00, 34593.57 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1496/1496 [00:00<00:00, 24786.60 examples/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:11<00:00, 11.82s/it]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.40it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.49it/s]

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.53s/it]
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 11863.06 examples/s]

[BERT-Base-German_3] eval_f1=0.6703106181694705 fitted in 52.68 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/BERT Transformer Models Non-Deterministic/BERT-Base-German_3/final_model
Operations are near-deterministic: False
Seed: 228075695

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 14000.48it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-german-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5233/5233 [00:00<00:00, 32401.33 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1496/1496 [00:00<00:00, 28098.01 examples/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.46it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.46it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.61it/s]

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:12<00:00, 12.55s/it]
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 10625.49 examples/s]

[BERT-Base-German_4] eval_f1=0.6767420535458127 fitted in 36.68 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/BERT Transformer Models Non-Deterministic/BERT-Base-German_4/final_model
Operations are near-deterministic: False
Seed: 54763537

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 16967.18it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-german-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5233/5233 [00:00<00:00, 35277.58 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1496/1496 [00:00<00:00, 27634.45 examples/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.50it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.16it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.38it/s]

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.95s/it]
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 11633.07 examples/s]

[BERT-Base-German_5] eval_f1=0.6736038738271651 fitted in 36.54 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/BERT Transformer Models Non-Deterministic/BERT-Base-German_5/final_model
Operations are near-deterministic: False
Seed: 75476292

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 17331.47it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-german-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5233/5233 [00:00<00:00, 33734.63 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1496/1496 [00:00<00:00, 25600.28 examples/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.50it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.37it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.89it/s]

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:08<00:00,  8.45s/it]
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 12092.91 examples/s]

[BERT-Base-German_6] eval_f1=0.6815833100100184 fitted in 37.19 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/BERT Transformer Models Non-Deterministic/BERT-Base-German_6/final_model
Operations are near-deterministic: False
Seed: 411604195

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 14890.93it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-german-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5233/5233 [00:00<00:00, 34585.29 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1496/1496 [00:00<00:00, 27309.35 examples/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.50it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.66it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.35it/s]

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.32s/it]
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 12938.99 examples/s]

[BERT-Base-German_7] eval_f1=0.670507925488835 fitted in 37.42 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/BERT Transformer Models Non-Deterministic/BERT-Base-German_7/final_model
Operations are near-deterministic: False
Seed: 2036765486

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 16131.94it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-german-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5233/5233 [00:00<00:00, 34601.43 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1496/1496 [00:00<00:00, 27214.71 examples/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.52it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.43it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.47it/s]

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:12<00:00, 12.30s/it]
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 12611.79 examples/s]

[BERT-Base-German_8] eval_f1=0.667003783984916 fitted in 36.53 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/BERT Transformer Models Non-Deterministic/BERT-Base-German_8/final_model
Operations are near-deterministic: False
Seed: 1013333145

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 14322.15it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-german-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5233/5233 [00:00<00:00, 33651.10 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1496/1496 [00:00<00:00, 27076.26 examples/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.61it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.94it/s]
Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.10it/s]

Writing model shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.29s/it]
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 13500.83 examples/s]

[BERT-Base-German_9] eval_f1=0.6680512787959177 fitted in 36.29 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/BERT Transformer Models Non-Deterministic/BERT-Base-German_9/final_model

### 8.3 Large Language Model

Finally, we want to train some foundational models. We use a pre-trained checkpoint and use Low Rank Adaptation (LoRA) for conversation style training. \
First of all, we define a system prompt for the model:

In [31]:
SYSTEM_PROMPT = ("Du bist ein hilfreicher Assistent, der die Stimmung (Sentiment) eines deutschen Textes klassifiziert. Antworte ausschließlich mit einem Wort: negativ, neutral, oder positiv.")

In [32]:
from peft import LoraConfig, get_peft_model, TaskType

We build `build_chat_template`. Note that we set `tokenize = False` on `apply_chat_format`. If it is set to `True` it might overflow.

In [33]:
def build_chat_example(tokenizer, 
                       text, 
                       label, 
                       max_length):
    
    """Formats one example using the model chat template, keeping the
    conversational structure intact, and masks the prompt tokens in the labels
    so loss is only computed on the assistant answer."""

    # force label to be a string
    label_str = str(label)
    
    messages_prompt = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": text},
    ]

    # define prompt format
    # contains system and user
    prompt_str = tokenizer.apply_chat_template(
        messages_prompt, 
        tokenize = False, # set to False to force string templating only 
        add_generation_prompt = True
    )

    # define full messages
    # contains system, user and assistant
    full_messages = messages_prompt + [{"role": "assistant", "content": label_str}]
    full_str = tokenizer.apply_chat_template(
        full_messages, 
        tokenize = False, # set to False to force string templating only 
        add_generation_prompt = False
    )

    # tokenize
    prompt_ids = tokenizer(prompt_str,
                           add_special_tokens = False)["input_ids"]
    full_ids = tokenizer(full_str,
                         add_special_tokens = False)["input_ids"]

    full_ids = full_ids[:max_length]
    labels = list(full_ids)
    prompt_len = min(len(prompt_ids), len(full_ids))
    
    for i in range(prompt_len):
        labels[i] = -100  # mask prompt tokens from the loss

    
    return {

        # force integers to be sure
        "input_ids": [int(i) for i in full_ids],
        "labels": [int(l) for l in labels],
    }

We can now use `build_chat_example` to build a dataset.

In [34]:
def build_dataset(tokenizer, 
                  texts, 
                  labels, 
                  max_length):
    
    #do a list comprehension for examples
    examples = [build_chat_example(tokenizer, t, l, max_length) for t, l in zip(texts, labels)]
    
    return Dataset.from_list(examples)

In [35]:
class PaddingCollator:
    
    """Pads input_ids and labels to the longest sequence in the batch (-100 for
    padded label positions so they don't contribute to loss)."""
    
    def __init__(self, tokenizer):
        self.tokenizer = tokenizer
        self.pad_id = tokenizer.pad_token_id or tokenizer.eos_token_id

    def __call__(self, features):
        max_len = max(len(f["input_ids"]) for f in features)

        # define empty lists to fill later
        input_ids, attention_mask, labels = [], [], []
        
        for f in features:
            pad_len = max_len - len(f["input_ids"])
            input_ids.append(f["input_ids"] + [self.pad_id] * pad_len)
            attention_mask.append([1] * len(f["input_ids"]) + [0] * pad_len)
            labels.append(f["labels"] + [-100] * pad_len)
        
        return {
            
            # return all as 64-bit integers
            "input_ids": torch.tensor(input_ids, dtype = torch.long),
            "attention_mask": torch.tensor(attention_mask, dtype = torch.long),
            "labels": torch.tensor(labels, dtype = torch.long),
        }

We define `generate_predictions`. Note that we set `tokenizer.padding_side = "left"` for predictions but set `tokenizer.padding_side = "right"` for training. \
It is necessary to do so in decoder-only models. `model.generate()` requires right padding, because decoder-only models will only attend at tokens before the current token. No PAD-tokens should be there or the model will be confused.

In [36]:
@torch.no_grad()
def generate_predictions(model, 
                         tokenizer, 
                         texts, 
                         label_set, 
                         max_new_tokens = 5, 
                         batch_size = 16):
    
    #no training
    model.eval()

    # needed for correct batched generation
    original_padding_side = tokenizer.padding_side
    tokenizer.padding_side = "left"
    
    preds = []
    
    for i in range(0, len(texts), batch_size):
        
        batch_texts = texts[i:i + batch_size]

        # list comprehension for prompts
        prompts = [
            tokenizer.apply_chat_template(
                [{"role": "system", "content": SYSTEM_PROMPT},
                 {"role": "user", "content": t}],
                tokenize = False, 
                add_generation_prompt = True,
            )
            for t in batch_texts
        ]

        # create tensors and send them to device
        inputs = tokenizer(prompts, 
                           return_tensors = "pt", 
                           padding = True).to(device) #device was defined in the beginning
        
        # create outputs
        out = model.generate(
            **inputs, max_new_tokens = max_new_tokens, do_sample = cfg.do_sample
        )
        decoded = tokenizer.batch_decode(out[:, inputs["input_ids"].shape[1]:],
                                          skip_special_tokens = True)
        
        for d in decoded:
            d_clean = d.strip().lower()
            match = next((lab for lab in label_set if lab in d_clean), label_set[0])
            
            # add results to preds
            preds.append(match)

    # restore original padding
    tokenizer.padding_side = original_padding_side
    
    return preds

We define a similar evaluation function as in logistic regression and encoder transformer.

In [37]:
def evaluate_generation(model, 
                        tokenizer, 
                        texts, 
                        true_labels, 
                        label_set):

    # use generate_predictions from above
    preds = generate_predictions(model, 
                                 tokenizer, 
                                 texts, 
                                 label_set)
    
    precision, recall, f1, _ = precision_recall_fscore_support(
        true_labels, 
        preds, 
        average = "macro", 
        zero_division = 0, 
        labels = list(label_set)
    )
    
    
    return {
        "accuracy": accuracy_score(true_labels, preds),
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "confusion_matrix": confusion_matrix(true_labels, 
                                             preds, 
                                             labels = list(label_set)).tolist(),
        "raw_predictions_sample": preds[:20],
    }

In [38]:
# specifically designed for Qwen 2
def fit_and_save_qwen(cfg,
                      name,
                      X_train_input, 
                      y_train_input, 
                      X_eval_input, 
                      y_eval_input,
                      X_test_input = None, 
                      y_test_input = None):

    # set seeds to be sure
    tf.set_seed(seed)
    generator = torch.Generator().manual_seed(seed)

    # define directory to use
    run_dir = Path(cfg.output_directory_foundation_nondeterministic) / name
    
    #make sure the directory exists
    run_dir.mkdir(parents = True, exist_ok = True)

    tokenizer = tf.AutoTokenizer.from_pretrained(cfg.model_checkpoint_foundation)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # needed for decoder-only models
    tokenizer.padding_side = "right"

    base_model = tf.AutoModelForCausalLM.from_pretrained(
        cfg.model_checkpoint_foundation, 
        dtype = torch.bfloat16 #half precision
    )

    # define LoRA config
    lora_config = LoraConfig(
        task_type = TaskType.CAUSAL_LM,
        r = cfg.lora_r,
        lora_alpha = cfg.lora_alpha,
        lora_dropout = cfg.lora_dropout,
        
        # attention modules for Qwen 2
        target_modules = ["q_proj", 
                          "k_proj", 
                          "v_proj", 
                          "o_proj"]
    )
    
    model = get_peft_model(base_model, 
                           lora_config)
    
    # build train dataset with function from above
    train_ds = build_dataset(tokenizer, 
                             X_train_input, 
                             y_train_input, 
                             cfg.max_length_foundation)

    # build test dataset with function from above
    eval_ds = build_dataset(tokenizer, 
                            X_eval_input, 
                            y_eval_input, 
                            cfg.max_length_foundation)
    
    collator = PaddingCollator(tokenizer)

    training_args = tf.TrainingArguments(
        output_dir = str(run_dir / "checkpoints"),
        learning_rate = cfg.learning_rate_foundation,
        per_device_train_batch_size = cfg.batch_size_foundation,
        per_device_eval_batch_size = cfg.batch_size_foundation,
        num_train_epochs = cfg.num_epochs_foundation,
        weight_decay = cfg.weight_decay_foundation,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        save_total_limit = 2,
        seed = seed,
        data_seed = seed,
        dataloader_num_workers = cfg.dataloader_num_workers_foundation,
        report_to = "none",
        logging_dir = str(run_dir / "logs"), # deprecated but we would have to set it as an env variable instead -> not going to do that
        bf16 = cfg.use_bf16_foundation,
        tf32 = cfg.use_tf32_foundation,
        dataloader_pin_memory = True,
    )

    trainer = tf.Trainer(
        model = model,
        args = training_args,
        train_dataset = train_ds,
        eval_dataset = eval_ds,
        data_collator = collator
    )

    start = perf_counter()
    trainer.train()
    fit_seconds = perf_counter() - start

    # save only LoRA adapter
    final_dir = run_dir / "final_adapter"
    model.save_pretrained(str(final_dir))
    tokenizer.save_pretrained(str(final_dir))

    # use function from above
    eval_metrics = evaluate_generation(model, 
                                       tokenizer, 
                                       X_eval_input, 
                                       y_eval_input, 
                                       cfg.label_set_foundation)

    # use for gold-standard annotations
    test_metrics = None
    if X_test_input is not None:
        test_metrics = evaluate_generation(model, 
                                           tokenizer, 
                                           X_test_input, 
                                           y_test_input, 
                                           cfg.label_set_foundation)

    # create metadata dict
    metadata = {
            "name": name,
            "timestamp": datetime.now().isoformat(),
            "model_checkpoint": cfg.model_checkpoint_foundation,
            "random_state": seed,
            "lora_config": {"r": cfg.lora_r, 
                            "alpha": cfg.lora_alpha, 
                            "dropout": cfg.lora_dropout},
            "hyperparameters": {
                "learning_rate": cfg.learning_rate_foundation,
                "batch_size": cfg.batch_size_foundation,
                "num_epochs": cfg.num_epochs_foundation,
                "weight_decay": cfg.weight_decay_foundation,
                "max_length": cfg.max_length_foundation,
            },
            "fit_seconds": fit_seconds,
            "eval_metrics": eval_metrics,
            "test_metrics": test_metrics,
            "final_adapter_path": str(final_dir),
            "CUDA_device_memory_used": torch.cuda.memory_reserved(0), # get info about needed GPU memory
            "torch_version": torch.__version__,
        }

        # save metadata to json
    with open(run_dir / "metadata.json", "w") as f:
        json.dump(metadata, 
                  f, 
                  indent = 2)

    # free up some memory
    del model, base_model, trainer
    torch.cuda.empty_cache()

    print(f"[{name}] eval_f1={eval_metrics['f1']:.4f} fitted in {fit_seconds:.2f} seconds and was saved to {final_dir}")
    
    return metadata

We can now fit the models. \
This time we do not need to include `del model ...` in this cell because we already defined it in the `fit_and_save_qwen` function. At the encoder, we had to add it manually to training, because it was not defined inside the function (we forgot to do it).

In [39]:
results_foundation = {}

# fit ten models
for x in range(cfg.n_models):

    # set each time
    seed, generator = set_determinism(cfg)
    
    meta = fit_and_save_qwen(
        cfg,
        cfg.name_prefix_foundation_nondeterministic + str(x), # name each model after run
        X_train,
        y_train,
        X_eval,
        y_eval,
        X_test,
        y_test
    )

    results_foundation[x] = meta

Operations are near-deterministic: False
Seed: 1275498656

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 11138.21it/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

[Qwen2-05B-Foundation_0] eval_f1=0.8637 fitted in 150.77 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Foundation Models Non-Deterministic/Qwen2-05B-Foundation_0/final_adapter
Operations are near-deterministic: False
Seed: 1449457112

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 14073.71it/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

[W807 00:14:30.532841746 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 681574400 bytes (free: 587005952, total: 16600465408).

[Qwen2-05B-Foundation_1] eval_f1=0.8624 fitted in 152.14 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Foundation Models Non-Deterministic/Qwen2-05B-Foundation_1/final_adapter
Operations are near-deterministic: False
Seed: 1311158967

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 14961.23it/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

[W807 00:17:16.249214822 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 681574400 bytes (free: 631046144, total: 16600465408).

[Qwen2-05B-Foundation_2] eval_f1=0.8622 fitted in 150.99 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Foundation Models Non-Deterministic/Qwen2-05B-Foundation_2/final_adapter
Operations are near-deterministic: False
Seed: 43204989

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 14528.07it/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

[Qwen2-05B-Foundation_3] eval_f1=0.8582 fitted in 150.58 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Foundation Models Non-Deterministic/Qwen2-05B-Foundation_3/final_adapter
Operations are near-deterministic: False
Seed: 1717083846

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 11354.26it/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

[W807 00:22:34.212075949 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 608174080 bytes (free: 339738624, total: 16600465408).

[Qwen2-05B-Foundation_4] eval_f1=0.8577 fitted in 148.03 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Foundation Models Non-Deterministic/Qwen2-05B-Foundation_4/final_adapter
Operations are near-deterministic: False
Seed: 972172179

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 16253.95it/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

[Qwen2-05B-Foundation_5] eval_f1=0.8633 fitted in 148.56 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Foundation Models Non-Deterministic/Qwen2-05B-Foundation_5/final_adapter
Operations are near-deterministic: False
Seed: 3247796

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 13231.96it/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

[Qwen2-05B-Foundation_6] eval_f1=0.8593 fitted in 148.42 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Foundation Models Non-Deterministic/Qwen2-05B-Foundation_6/final_adapter
Operations are near-deterministic: False
Seed: 1977599447

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 13675.44it/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

[W807 00:30:30.081827839 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 637534208 bytes (free: 344457216, total: 16600465408).

[Qwen2-05B-Foundation_7] eval_f1=0.8619 fitted in 148.49 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Foundation Models Non-Deterministic/Qwen2-05B-Foundation_7/final_adapter
Operations are near-deterministic: False
Seed: 875049050

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 12872.36it/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

[W807 00:33:03.095309075 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 622854144 bytes (free: 554172416, total: 16600465408).

[Qwen2-05B-Foundation_8] eval_f1=0.8615 fitted in 148.26 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Foundation Models Non-Deterministic/Qwen2-05B-Foundation_8/final_adapter
Operations are near-deterministic: False
Seed: 855680334

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 13880.34it/s]
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

[W807 00:35:38.564524652 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 633339904 bytes (free: 614989824, total: 16600465408).

[Qwen2-05B-Foundation_9] eval_f1=0.8527 fitted in 148.78 seconds and was saved to /home/simon/Documents/Machine learning Seminar/Models/Foundation Models Non-Deterministic/Qwen2-05B-Foundation_9/final_adapter

---
## 9 Inference

For H1b, we conduct 20 inference runs per checkpoint per architecture. After each run the logits are compared. \
\
We run each of the ten checkpoints a total of 20 times. To save the results as a .csv we would need multiple files. We have a more efficient way of storing multi-dimensional data: tensors. \
All results get stored in a four-dimensional tensor. \
The tensor is then stored as binary. \
Afterwards we compare the first run of each model to the first run of every other model.

### 9.1 Logistic regression

In [40]:
# define function to build output tensor
def build_logit_tensor(model_dir, 
                       model_name_prefix, 
                       dataset, 
                       n_models, 
                       n_runs):
    
    """Returns tensor of shape (n_models, n_runs, n_samples, n_classes) —
    raw decision_function output per run, per model."""
    
    pipeline0 = joblib.load(Path(model_dir) / f"{model_name_prefix}0.joblib")
    n_classes = len(pipeline0.named_steps["clf"].classes_)
    n_samples = len(dataset)

    tensor = np.empty((n_models, 
                       n_runs, 
                       n_samples, 
                       n_classes), 
                      dtype = np.float64) # double-precision

    for m in range(n_models):
        
        pipeline = joblib.load(Path(model_dir) / f"{model_name_prefix}{m}.joblib")
        
        for r in range(n_runs):
            tensor[m, r] = pipeline.decision_function(dataset)

    return tensor

In [41]:
# build actual tensor
logit_tensor = build_logit_tensor(
    cfg.output_directory_logistic_nondeterministic,
    cfg.name_prefix_logistic_nondeterministic,
    dataset_user["message"].tolist(),
    cfg.n_models,
    cfg.n_runs,
)

# save to file
np.save(Path(cfg.output_directory_logistic_nondeterministic) / "logit_tensor_nondeterministic.npy", logit_tensor)
print("Tensor shape:", logit_tensor.shape)

Tensor shape: (10, 20, 2376, 3)

In [42]:
# within-model: do all 20 runs for model n agree exactly?
for i in range(cfg.n_models):

    # compute the maximum absolute difference
    within_model_diff = np.max(np.abs(logit_tensor[i] - logit_tensor[i, 0]))
    print(f"Max diff within model {i} across 20 runs:", within_model_diff)

# between models: does model 0's first run match model n's first run?
for i in range(cfg.n_models):
    
    between_model_diff = np.max(np.abs(logit_tensor[0, 0] - logit_tensor[i, 0]))
    print(f"Max diff between model 0 and model {i} (run 0):", between_model_diff)

# pairwise matrix
n_models = logit_tensor.shape[0]
pairwise_max_diff = np.zeros((n_models, n_models))

for i in range(n_models):
    
    for j in range(n_models):
        
        pairwise_max_diff[i, j] = np.max(np.abs(logit_tensor[i, 0] - logit_tensor[j, 0]))

print(pd.DataFrame(pairwise_max_diff))

Max diff within model 0 across 20 runs: 0.0
Max diff within model 1 across 20 runs: 0.0
Max diff within model 2 across 20 runs: 0.0
Max diff within model 3 across 20 runs: 0.0
Max diff within model 4 across 20 runs: 0.0
Max diff within model 5 across 20 runs: 0.0
Max diff within model 6 across 20 runs: 0.0
Max diff within model 7 across 20 runs: 0.0
Max diff within model 8 across 20 runs: 0.0
Max diff within model 9 across 20 runs: 0.0
Max diff between model 0 and model 0 (run 0): 0.0
Max diff between model 0 and model 1 (run 0): 0.0
Max diff between model 0 and model 2 (run 0): 0.0
Max diff between model 0 and model 3 (run 0): 0.0
Max diff between model 0 and model 4 (run 0): 0.0
Max diff between model 0 and model 5 (run 0): 0.0
Max diff between model 0 and model 6 (run 0): 0.0
Max diff between model 0 and model 7 (run 0): 0.0
Max diff between model 0 and model 8 (run 0): 0.0
Max diff between model 0 and model 9 (run 0): 0.0
     0    1    2    3    4    5    6    7    8    9
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

### 9.2 Encoder-Transformer

In [19]:
@torch.no_grad()
def get_logits_for_model(model_dir, 
                         texts, 
                         max_length, 
                         batch_size, 
                         device):
    
    """Runs one forward pass over the full dataset and returns raw logits,
    shape (n_samples, n_classes)."""
    
    tokenizer = tf.AutoTokenizer.from_pretrained(model_dir)
    model = tf.AutoModelForSequenceClassification.from_pretrained(model_dir).to(device)
    
    # specify eval
    model.eval()

    all_logits = []
    
    for i in range(0, len(texts), batch_size):
        
        # inference
        batch = texts[i:i + batch_size]
        inputs = tokenizer(
            batch, 
            return_tensors = "pt", 
            truncation = True,
            padding = "max_length", 
            max_length = max_length
            
        ).to(device)
        
        outputs = model(**inputs)
        all_logits.append(outputs.logits.cpu().numpy())

    # save memory
    del model
    torch.cuda.empty_cache()

    return np.concatenate(all_logits, axis = 0)  # (n_samples, n_classes)

In [20]:
# build tensor with same shape as above
def build_encoder_logit_tensor(output_dir, 
                               name_prefix, 
                               texts, 
                               max_length,
                               n_models, 
                               n_runs, 
                               batch_size, 
                               device):
    
    """Returns tensor of shape (n_models, n_runs, n_samples, n_classes)."""
    
    n_samples = len(texts)
    n_classes = None
    tensor = None

    for m in range(n_models):
        
        model_path = Path(output_dir) / f"{name_prefix}{m}" / "final_model"
        
        for r in range(n_runs):

            # use logit function from above
            logits = get_logits_for_model(str(model_path), 
                                          texts, 
                                          max_length, 
                                          batch_size, 
                                          device)
            
            if tensor is None:
                n_classes = logits.shape[1]
                tensor = np.empty((n_models, 
                                   n_runs, 
                                   n_samples, 
                                   n_classes), 
                                  dtype = np.float64) # double precision
                
            tensor[m, r] = logits
            
            print(f"model {m}, run {r} done")

    return tensor

In [21]:
# build actual tensor
encoder_logit_tensor = build_encoder_logit_tensor(
    output_dir = cfg.output_directory_encoder_nondeterministic,
    name_prefix = cfg.name_prefix_encoder_nondeterministic,
    texts = dataset_user["message"].tolist(),
    max_length = cfg.max_length,
    n_models = cfg.n_models,
    n_runs = cfg.n_runs,
    batch_size = cfg.batch_size,
    device = cfg.device,
)

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15946.42it/s]

model 0, run 0 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16796.27it/s]

model 0, run 1 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17395.49it/s]

model 0, run 2 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16332.58it/s]

model 0, run 3 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14947.26it/s]

model 0, run 4 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19909.67it/s]

model 0, run 5 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18063.40it/s]

model 0, run 6 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15663.76it/s]

model 0, run 7 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14918.69it/s]

model 0, run 8 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16835.51it/s]

model 0, run 9 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14413.42it/s]

model 0, run 10 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16434.78it/s]

model 0, run 11 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17479.89it/s]

model 0, run 12 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20746.00it/s]

model 0, run 13 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19319.73it/s]

model 0, run 14 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16371.27it/s]

model 0, run 15 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16208.86it/s]

model 0, run 16 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16118.68it/s]

model 0, run 17 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15770.42it/s]

model 0, run 18 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17880.28it/s]

model 0, run 19 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15978.15it/s]

model 1, run 0 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16023.70it/s]

model 1, run 1 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 23890.70it/s]

model 1, run 2 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18273.26it/s]

model 1, run 3 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15184.71it/s]

model 1, run 4 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15797.31it/s]

model 1, run 5 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15335.52it/s]

model 1, run 6 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17187.67it/s]

model 1, run 7 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16318.35it/s]

model 1, run 8 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16780.56it/s]

model 1, run 9 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17017.32it/s]

model 1, run 10 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 13110.67it/s]

model 1, run 11 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16696.14it/s]

model 1, run 12 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15781.05it/s]

model 1, run 13 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 13898.73it/s]

model 1, run 14 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16017.92it/s]

model 1, run 15 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17680.78it/s]

model 1, run 16 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17068.31it/s]

model 1, run 17 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16775.55it/s]

model 1, run 18 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20915.33it/s]

model 1, run 19 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18202.24it/s]

model 2, run 0 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17210.12it/s]

model 2, run 1 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14425.75it/s]

model 2, run 2 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 13872.43it/s]

model 2, run 3 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 21236.18it/s]

model 2, run 4 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15473.16it/s]

model 2, run 5 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 13443.50it/s]

model 2, run 6 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18072.70it/s]

model 2, run 7 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15229.15it/s]

model 2, run 8 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15399.39it/s]

model 2, run 9 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 23877.85it/s]

model 2, run 10 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17673.00it/s]

model 2, run 11 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 22401.42it/s]

model 2, run 12 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17084.57it/s]

model 2, run 13 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18832.91it/s]

model 2, run 14 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14325.25it/s]

model 2, run 15 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 13396.71it/s]

model 2, run 16 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15499.90it/s]

model 2, run 17 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16957.42it/s]

model 2, run 18 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15320.20it/s]

model 2, run 19 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16348.10it/s]

model 3, run 0 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14146.41it/s]

model 3, run 1 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 11233.99it/s]

model 3, run 2 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17267.58it/s]

model 3, run 3 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18596.94it/s]

model 3, run 4 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19847.33it/s]

model 3, run 5 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15154.41it/s]

model 3, run 6 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15118.00it/s]

model 3, run 7 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17422.09it/s]

model 3, run 8 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15914.81it/s]

model 3, run 9 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16062.78it/s]

model 3, run 10 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 12431.69it/s]

model 3, run 11 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15937.37it/s]

model 3, run 12 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19945.47it/s]

model 3, run 13 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18168.12it/s]

model 3, run 14 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14986.31it/s]

model 3, run 15 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20025.54it/s]

model 3, run 16 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17557.43it/s]

model 3, run 17 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 13836.00it/s]

model 3, run 18 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18181.83it/s]

model 3, run 19 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18110.35it/s]

model 4, run 0 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18765.83it/s]

model 4, run 1 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15251.46it/s]

model 4, run 2 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15485.95it/s]

model 4, run 3 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 21229.23it/s]

model 4, run 4 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15847.79it/s]

model 4, run 5 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17820.94it/s]

model 4, run 6 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20158.17it/s]

model 4, run 7 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18628.17it/s]

model 4, run 8 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17625.34it/s]

model 4, run 9 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14116.09it/s]

model 4, run 10 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 21234.58it/s]

model 4, run 11 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14947.26it/s]

model 4, run 12 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15646.61it/s]

model 4, run 13 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19040.47it/s]

model 4, run 14 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16240.08it/s]

model 4, run 15 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16047.80it/s]

model 4, run 16 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14515.66it/s]

model 4, run 17 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16846.95it/s]

model 4, run 18 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15452.46it/s]

model 4, run 19 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 21719.27it/s]

model 5, run 0 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19252.23it/s]

model 5, run 1 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14314.06it/s]

model 5, run 2 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15336.92it/s]

model 5, run 3 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14634.59it/s]

model 5, run 4 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16413.35it/s]

model 5, run 5 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16243.84it/s]

model 5, run 6 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16554.84it/s]

model 5, run 7 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16732.93it/s]

model 5, run 8 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16668.74it/s]

model 5, run 9 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15643.71it/s]

model 5, run 10 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17006.68it/s]

model 5, run 11 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15775.44it/s]

model 5, run 12 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16305.10it/s]

model 5, run 13 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15452.17it/s]

model 5, run 14 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 21500.47it/s]

model 5, run 15 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 22271.82it/s]

model 5, run 16 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 13440.28it/s]

model 5, run 17 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15477.99it/s]

model 5, run 18 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20652.99it/s]

model 5, run 19 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17068.31it/s]

model 6, run 0 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20345.47it/s]

model 6, run 1 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17798.36it/s]

model 6, run 2 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20006.53it/s]

model 6, run 3 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14136.44it/s]

model 6, run 4 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14223.74it/s]

model 6, run 5 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20002.26it/s]

model 6, run 6 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14174.23it/s]

model 6, run 7 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17677.82it/s]

model 6, run 8 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17878.00it/s]

model 6, run 9 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17608.40it/s]

model 6, run 10 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16430.30it/s]

model 6, run 11 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 12981.66it/s]

model 6, run 12 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17354.67it/s]

model 6, run 13 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20111.05it/s]

model 6, run 14 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14353.78it/s]

model 6, run 15 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16153.88it/s]

model 6, run 16 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15587.60it/s]

model 6, run 17 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 22966.52it/s]

model 6, run 18 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18183.01it/s]

model 6, run 19 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16202.63it/s]

model 7, run 0 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17324.36it/s]

model 7, run 1 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17370.76it/s]

model 7, run 2 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 21705.29it/s]

model 7, run 3 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19602.29it/s]

model 7, run 4 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19860.42it/s]

model 7, run 5 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 22791.43it/s]

model 7, run 6 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 6572.97it/s]

model 7, run 7 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16936.98it/s]

model 7, run 8 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15516.45it/s]

model 7, run 9 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14424.51it/s]

model 7, run 10 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17098.78it/s]

model 7, run 11 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20444.14it/s]

model 7, run 12 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17111.62it/s]

model 7, run 13 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18479.14it/s]

model 7, run 14 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15598.56it/s]

model 7, run 15 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 21363.72it/s]

model 7, run 16 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19453.92it/s]

model 7, run 17 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20929.87it/s]

model 7, run 18 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 13611.49it/s]

model 7, run 19 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14741.82it/s]

model 8, run 0 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16206.99it/s]

model 8, run 1 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14245.61it/s]

model 8, run 2 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16873.93it/s]

model 8, run 3 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15062.36it/s]

model 8, run 4 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18304.60it/s]

model 8, run 5 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 18912.33it/s]

model 8, run 6 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 12386.21it/s]

model 8, run 7 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19612.77it/s]

model 8, run 8 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16740.57it/s]

model 8, run 9 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16193.60it/s]

model 8, run 10 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14491.46it/s]

model 8, run 11 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19590.44it/s]

model 8, run 12 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17169.82it/s]

model 8, run 13 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17985.94it/s]

model 8, run 14 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16230.39it/s]

model 8, run 15 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15729.81it/s]

model 8, run 16 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14865.03it/s]

model 8, run 17 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19003.99it/s]

model 8, run 18 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14250.67it/s]

model 8, run 19 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14160.90it/s]

model 9, run 0 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16107.28it/s]

model 9, run 1 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15616.18it/s]

model 9, run 2 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16324.36it/s]

model 9, run 3 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17063.13it/s]

model 9, run 4 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14853.24it/s]

model 9, run 5 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15933.46it/s]

model 9, run 6 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 20459.03it/s]

model 9, run 7 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17776.60it/s]

model 9, run 8 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15264.44it/s]

model 9, run 9 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 21505.96it/s]

model 9, run 10 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 14206.48it/s]

model 9, run 11 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15958.79it/s]

model 9, run 12 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 13702.20it/s]

model 9, run 13 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16025.84it/s]

model 9, run 14 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 19781.20it/s]

model 9, run 15 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15695.55it/s]

model 9, run 16 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 16692.51it/s]

model 9, run 17 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 21767.50it/s]

model 9, run 18 done

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 17534.79it/s]

model 9, run 19 done

In [22]:
# verify
print("Tensor shape:", encoder_logit_tensor.shape)  # expect (10, 20, 2376, 3)
np.save(Path(cfg.output_directory_encoder_nondeterministic) / "logit_tensor_nondeterministic.npy", encoder_logit_tensor)

Tensor shape: (10, 20, 2376, 3)

In [23]:
# logit difference computations identical to logistic regression

# within-model: do all 20 runs for model n agree exactly?
for i in range(cfg.n_models):

    # compute the maximum absolute difference
    within_model_diff = np.max(np.abs(encoder_logit_tensor[i] - encoder_logit_tensor[i, 0]))
    print(f"Max diff within model {i} across 20 runs:", within_model_diff)

# between models: does model 0's first run match model n's first run?
for i in range(cfg.n_models):
    
    between_model_diff = np.max(np.abs(encoder_logit_tensor[0, 0] - encoder_logit_tensor[i, 0]))
    print(f"Max diff between model 0 and model {i} (run 0):", between_model_diff)

# pairwise matrix
n_models = encoder_logit_tensor.shape[0]
pairwise_max_diff = np.zeros((n_models, n_models))

for i in range(n_models):
    
    for j in range(n_models):
        
        pairwise_max_diff[i, j] = np.max(np.abs(encoder_logit_tensor[i, 0] - encoder_logit_tensor[j, 0]))

print(pd.DataFrame(pairwise_max_diff))

Max diff within model 0 across 20 runs: 0.0
Max diff within model 1 across 20 runs: 0.0
Max diff within model 2 across 20 runs: 0.0
Max diff within model 3 across 20 runs: 0.0
Max diff within model 4 across 20 runs: 0.0
Max diff within model 5 across 20 runs: 0.0
Max diff within model 6 across 20 runs: 0.0
Max diff within model 7 across 20 runs: 0.0
Max diff within model 8 across 20 runs: 0.0
Max diff within model 9 across 20 runs: 0.0
Max diff between model 0 and model 0 (run 0): 0.0
Max diff between model 0 and model 1 (run 0): 2.2711198925971985
Max diff between model 0 and model 2 (run 0): 2.474169611930847
Max diff between model 0 and model 3 (run 0): 3.1113412380218506
Max diff between model 0 and model 4 (run 0): 2.6468162536621094
Max diff between model 0 and model 5 (run 0): 2.442875623703003
Max diff between model 0 and model 6 (run 0): 2.796862244606018
Max diff between model 0 and model 7 (run 0): 1.7098917961120605
Max diff between model 0 and model 8 (run 0): 2.4137409925460815
Max diff between model 0 and model 9 (run 0): 2.4195491075515747
          0         1         2         3         4         5         6  \
0  0.000000  2.271120  2.474170  3.111341  2.646816  2.442876  2.796862
1  2.271120  0.000000  2.338203  1.983605  1.755901  1.710217  2.003810
2  2.474170  2.338203  0.000000  2.089941  2.674139  2.282652  2.390886
3  3.111341  1.983605  2.089941  0.000000  1.997503  2.333840  2.194353
4  2.646816  1.755901  2.674139  1.997503  0.000000  2.220414  1.903952
5  2.442876  1.710217  2.282652  2.333840  2.220414  0.000000  1.908669
6  2.796862  2.003810  2.390886  2.194353  1.903952  1.908669  0.000000
7  1.709892  2.150206  1.868494  1.977437  1.929434  1.939141  2.478889
8  2.413741  1.904841  2.104538  2.235797  2.588456  2.230602  2.252860
9  2.419549  2.166438  2.133333  2.270355  2.701790  2.160166  2.554953

          7         8         9
0  1.709892  2.413741  2.419549
1  2.150206  1.904841  2.166438
2  1.868494  2.104538  2.133333
3  1.977437  2.235797  2.270355
4  1.929434  2.588456  2.701790
5  1.939141  2.230602  2.160166
6  2.478889  2.252860  2.554953
7  0.000000  2.795604  2.209111
8  2.795604  0.000000  2.120605
9  2.209111  2.120605  0.000000

### 9.3 Foundation model

In [48]:
from peft import PeftModel

In [49]:
def get_label_token_ids(tokenizer, 
                        label_set):
    
    """Maps each label string to the token id it would start with, matching
    how it appears right after the chat template's generation prompt."""
    
    label_token_ids = []
    
    for label in label_set:
        ids = tokenizer.encode(label, 
                               add_special_tokens = False)
        
        label_token_ids.append(ids[0])  # first token of the label
        
    return label_token_ids

In [50]:
@torch.no_grad()
def get_qwen_class_logits(adapter_dir, 
                          base_checkpoint, 
                          texts, 
                          label_set,
                          max_length, 
                          batch_size, 
                          device):
    
    """Single forward pass per batch; extracts next-token logits restricted
    to the label vocabulary. Returns (n_samples, n_classes)."""
    
    tokenizer = tf.AutoTokenizer.from_pretrained(adapter_dir)
    
    if tokenizer.pad_token is None:
        
        tokenizer.pad_token = tokenizer.eos_token
        
    tokenizer.padding_side = "left"  # last token = last real position for every row

    base_model = tf.AutoModelForCausalLM.from_pretrained(base_checkpoint, 
                                                      torch_dtype = torch.float16) # half-precision
    
    model = PeftModel.from_pretrained(base_model, 
                                      adapter_dir).to(device)

    
    model.eval()

    # use function from above
    label_token_ids = get_label_token_ids(tokenizer, 
                                          label_set)

    all_logits = []
    
    for i in range(0, len(texts), batch_size):
        
        batch_texts = texts[i:i + batch_size]
        prompts = [
            tokenizer.apply_chat_template(
                [{"role": "system", "content": SYSTEM_PROMPT},
                 {"role": "user", "content": t}],
                tokenize = False, 
                add_generation_prompt = True,
            )
            for t in batch_texts
        ]
        
        inputs = tokenizer(prompts, 
                           return_tensors = "pt", 
                           padding = True,
                           truncation = True, 
                           max_length = max_length).to(device)

        outputs = model(**inputs)
        last_token_logits = outputs.logits[:, -1, :]
        class_logits = last_token_logits[:, label_token_ids]  # (batch, n_classes)
        all_logits.append(class_logits.float().cpu().numpy())

    # save memory
    del model, base_model
    torch.cuda.empty_cache()

    return np.concatenate(all_logits, axis = 0)  # (n_samples, n_classes)

In [51]:
# define function to build tensor
def build_qwen_logit_tensor(output_dir, 
                            name_prefix, 
                            base_checkpoint, 
                            texts, 
                            label_set,
                            max_length, 
                            n_models, 
                            n_runs, 
                            batch_size, 
                            device):
    
    """Returns array of shape (n_models, n_runs, n_samples, n_classes)."""
    
    n_samples = len(texts)
    n_classes = len(label_set)
    tensor = np.empty((n_models, 
                       n_runs, 
                       n_samples, 
                       n_classes), 
                      dtype = np.float64) # double precision

    for m in range(n_models):
        
        adapter_path = Path(output_dir) / f"{name_prefix}{m}" / "final_adapter"
        
        for r in range(n_runs):
            
            tensor[m, r] = get_qwen_class_logits(
                str(adapter_path), 
                base_checkpoint, 
                texts, 
                label_set,
                max_length, 
                batch_size, 
                device
            )
            
            print(f"model {m}, run {r} done")

    return tensor

In [52]:
# build actual tensor
qwen_logit_tensor = build_qwen_logit_tensor(
    output_dir = cfg.output_directory_foundation_nondeterministic,
    name_prefix = cfg.name_prefix_foundation_nondeterministic,
    base_checkpoint = cfg.model_checkpoint_foundation,
    texts = dataset_user["message"].tolist(),
    label_set = cfg.label_set_foundation,
    max_length = cfg.max_length_foundation,
    n_models = cfg.n_models,
    n_runs = cfg.n_runs,
    batch_size = cfg.batch_size,
    device = cfg.device,
)

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4142.66it/s]
[W807 00:45:06.438880105 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 935854080, total: 16600465408).

model 0, run 0 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5294.62it/s]
[W807 00:45:19.423099332 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 1 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3155.09it/s]
[W807 00:45:32.498445851 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 2 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3563.99it/s]
[W807 00:45:45.505479266 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 3 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4442.52it/s]
[W807 00:45:58.440013483 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 4 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3825.64it/s]
[W807 00:46:11.392517782 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 5 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3222.73it/s]
[W807 00:46:24.262189772 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 6 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4654.90it/s]
[W807 00:46:37.221934570 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 7 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4017.21it/s]
[W807 00:46:49.125101660 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 8 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3818.61it/s]
[W807 00:47:02.021858588 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 9 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4005.85it/s]
[W807 00:47:15.949875714 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 10 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3066.09it/s]
[W807 00:47:28.909783663 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 11 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3763.85it/s]
[W807 00:47:41.837936152 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 12 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3620.21it/s]
[W807 00:47:54.609408012 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 13 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3957.97it/s]
[W807 00:48:07.599941359 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 14 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4144.31it/s]
[W807 00:48:20.556503621 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 15 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3691.61it/s]
[W807 00:48:33.576355613 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 16 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4444.21it/s]
[W807 00:48:46.547345243 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 17 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3680.28it/s]
[W807 00:48:59.532028433 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 18 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5041.79it/s]
[W807 00:49:12.509793765 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 0, run 19 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4467.75it/s]
[W807 00:49:25.396286061 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 0 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4486.27it/s]
[W807 00:49:38.335720141 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 1 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4167.22it/s]
[W807 00:49:51.342833236 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 2 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3536.67it/s]
[W807 00:50:03.104407537 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 3 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4442.23it/s]
[W807 00:50:16.017081205 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 4 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4406.96it/s]
[W807 00:50:29.913528125 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 5 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4869.66it/s]
[W807 00:50:42.665603204 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 6 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4528.31it/s]
[W807 00:50:55.256673969 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 7 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3709.51it/s]
[W807 00:51:07.047498886 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 8 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4012.72it/s]
[W807 00:51:20.786051465 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 9 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3873.77it/s]
[W807 00:51:33.362736938 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 10 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4984.38it/s]
[W807 00:51:45.130393732 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 11 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3711.76it/s]
[W807 00:51:58.053574779 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 12 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4842.65it/s]
[W807 00:52:11.649851177 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 13 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5033.26it/s]
[W807 00:52:24.388975687 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 14 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3916.59it/s]
[W807 00:52:36.114574600 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 15 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4968.99it/s]
[W807 00:52:49.829787038 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 16 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4682.04it/s]
[W807 00:53:02.418733072 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 17 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4747.69it/s]
[W807 00:53:15.160135211 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 18 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4754.20it/s]
[W807 00:53:27.931568866 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 1, run 19 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4079.69it/s]
[W807 00:53:40.532259330 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 0 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3706.68it/s]
[W807 00:53:53.382332662 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 1 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4338.49it/s]
[W807 00:54:06.155091238 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 2 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5035.05it/s]
[W807 00:54:18.909303232 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 3 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3753.28it/s]
[W807 00:54:31.546338993 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 4 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 2825.58it/s]
[W807 00:54:44.505217441 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 5 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4265.52it/s]
[W807 00:54:57.298839601 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 6 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4796.17it/s]
[W807 00:55:09.924402431 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 7 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4572.00it/s]
[W807 00:55:22.763297144 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 8 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4014.15it/s]
[W807 00:55:35.506628774 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 9 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3872.25it/s]
[W807 00:55:48.173296052 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 10 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3850.90it/s]
[W807 00:56:00.942476992 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 11 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4192.73it/s]
[W807 00:56:13.676930418 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 12 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5060.48it/s]
[W807 00:56:26.440261536 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 13 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4749.69it/s]
[W807 00:56:38.121115224 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 14 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4021.42it/s]
[W807 00:56:51.903515621 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 15 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4882.34it/s]
[W807 00:57:04.649735461 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 16 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4790.30it/s]
[W807 00:57:17.344567812 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 17 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5243.67it/s]
[W807 00:57:30.175450039 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 18 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3946.52it/s]
[W807 00:57:42.923362486 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 2, run 19 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3789.59it/s]
[W807 00:57:55.695378017 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 0 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4331.17it/s]
[W807 00:58:08.322994877 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 1 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4465.76it/s]
[W807 00:58:20.108660079 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 2 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3927.77it/s]
[W807 00:58:33.858818804 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 3 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3902.37it/s]
[W807 00:58:46.468339727 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 4 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3795.34it/s]
[W807 00:58:59.239739093 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 5 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4977.38it/s]
[W807 00:59:11.011515585 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 6 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3878.50it/s]
[W807 00:59:24.673296875 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 7 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4810.80it/s]
[W807 00:59:37.452347100 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 8 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4815.75it/s]
[W807 00:59:50.332674850 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 9 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4183.89it/s]
[W807 01:00:02.100373377 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 10 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4802.86it/s]
[W807 01:00:15.665390143 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 11 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4689.59it/s]
[W807 01:00:28.424497131 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 12 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5087.88it/s]
[W807 01:00:41.196089956 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 13 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3810.51it/s]
[W807 01:00:53.773834431 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 14 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5004.04it/s]
[W807 01:01:06.614502428 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 15 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3928.98it/s]
[W807 01:01:19.360623929 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 16 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4462.58it/s]
[W807 01:01:31.095966714 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 17 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5367.18it/s]
[W807 01:01:44.755007190 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 18 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3901.45it/s]
[W807 01:01:57.545508610 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 3, run 19 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4681.76it/s]
[W807 01:02:10.337882127 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 0 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4732.26it/s]
[W807 01:02:22.914258812 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 1 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3989.83it/s]
[W807 01:02:35.658521541 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 2 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4922.59it/s]
[W807 01:02:48.513577774 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 3 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4481.64it/s]
[W807 01:03:00.101295350 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 4 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3867.11it/s]
[W807 01:03:13.866711443 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 5 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3989.30it/s]
[W807 01:03:26.652993756 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 6 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4857.45it/s]
[W807 01:03:39.420565291 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 7 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4349.52it/s]
[W807 01:03:51.044039307 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 8 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4010.58it/s]
[W807 01:04:04.829500473 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 9 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4833.43it/s]
[W807 01:04:17.600634287 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 10 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5101.47it/s]
[W807 01:04:30.198545986 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 11 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4958.03it/s]
[W807 01:04:42.958784900 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 12 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4341.60it/s]
[W807 01:04:55.753218605 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 13 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4313.93it/s]
[W807 01:05:08.482616463 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 14 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4122.39it/s]
[W807 01:05:20.117327047 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 15 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4907.30it/s]
[W807 01:05:33.846439492 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 16 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3954.24it/s]
[W807 01:05:46.596949116 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 17 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3878.80it/s]
[W807 01:05:59.247322901 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 18 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4006.64it/s]
[W807 01:06:11.973488349 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 4, run 19 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4782.18it/s]
[W807 01:06:24.721312755 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 5, run 0 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5096.53it/s]
[W807 01:06:37.322511956 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 5, run 1 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5099.67it/s]
[W807 01:06:49.081795544 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 5, run 2 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3545.08it/s]
[W807 01:07:02.858841655 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 5, run 3 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3878.25it/s]
[W807 01:07:15.608126806 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 5, run 4 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5332.62it/s]
[W807 01:07:28.168654895 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 5, run 5 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5206.32it/s]
[W807 01:07:40.900370561 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 5, run 6 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5135.46it/s]
[W807 01:07:53.665711333 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 5, run 7 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5005.65it/s]
[W807 01:08:06.213123661 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 5, run 8 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5104.70it/s]
[W807 01:08:18.951619360 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1286078464, total: 16600465408).

model 5, run 9 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3978.10it/s]
[W807 01:08:31.762719950 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1283981312, total: 16600465408).

model 5, run 10 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4767.60it/s]
[W807 01:08:44.487542385 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1283981312, total: 16600465408).

model 5, run 11 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 5305.36it/s]
[W807 01:08:56.055748109 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1283981312, total: 16600465408).

model 5, run 12 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4704.97it/s]
[W807 01:09:10.429915222 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 5, run 13 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4517.98it/s]
[W807 01:09:23.390475500 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 5, run 14 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4105.15it/s]
[W807 01:09:36.200931761 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 5, run 15 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4683.16it/s]
[W807 01:09:49.164276714 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 5, run 16 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4423.62it/s]
[W807 01:10:01.135176638 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 5, run 17 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4139.44it/s]
[W807 01:10:14.920320743 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 5, run 18 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4282.28it/s]
[W807 01:10:27.906498137 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 5, run 19 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4543.72it/s]
[W807 01:10:40.823108512 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 0 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3866.59it/s]
[W807 01:10:53.726284276 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 1 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3358.10it/s]
[W807 01:11:06.486969202 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 2 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4665.34it/s]
[W807 01:11:19.426636757 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 3 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3394.19it/s]
[W807 01:11:32.346670543 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 4 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4239.86it/s]
[W807 01:11:44.109459754 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 5 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4527.82it/s]
[W807 01:11:57.109463914 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 6 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3540.86it/s]
[W807 01:12:10.048952968 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 7 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4591.12it/s]
[W807 01:12:23.918331427 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 8 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4463.19it/s]
[W807 01:12:36.668018877 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 9 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4198.57it/s]
[W807 01:12:49.617665159 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 10 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3569.96it/s]
[W807 01:13:02.533698566 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 11 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3703.76it/s]
[W807 01:13:15.288558676 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 12 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4651.32it/s]
[W807 01:13:28.228870380 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 13 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3358.70it/s]
[W807 01:13:41.145267375 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 14 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3469.36it/s]
[W807 01:13:53.932023646 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 15 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4272.31it/s]
[W807 01:14:06.860931222 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1294467072, total: 16600465408).

model 6, run 16 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3592.87it/s]
[W807 01:14:19.027272422 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 920584192, total: 16600465408).

model 6, run 17 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4770.78it/s]
[W807 01:14:33.148017632 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 920584192, total: 16600465408).

model 6, run 18 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4212.94it/s]
[W807 01:14:45.920464699 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 920584192, total: 16600465408).

model 6, run 19 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3522.36it/s]
[W807 01:14:58.866520183 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 920584192, total: 16600465408).

model 7, run 0 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3667.90it/s]
[W807 01:15:11.886451099 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 920584192, total: 16600465408).

model 7, run 1 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4259.15it/s]
[W807 01:15:24.731399118 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 920584192, total: 16600465408).

model 7, run 2 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4363.78it/s]
[W807 01:15:37.638224309 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 920584192, total: 16600465408).

model 7, run 3 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3300.61it/s]
[W807 01:15:50.568954358 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 920584192, total: 16600465408).

model 7, run 4 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4568.27it/s]
[W807 01:16:03.495308924 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 920584192, total: 16600465408).

model 7, run 5 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4544.07it/s]
[W807 01:16:16.243894939 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 920584192, total: 16600465408).

model 7, run 6 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3997.23it/s]
[W807 01:16:29.188653928 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 920584192, total: 16600465408).

model 7, run 7 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 2955.81it/s]
[W807 01:16:42.277925010 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 8 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 2999.56it/s]
[W807 01:16:55.424481106 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 9 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3930.47it/s]
[W807 01:17:08.376953812 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 10 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3107.35it/s]
[W807 01:17:21.349906238 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 11 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4350.77it/s]
[W807 01:17:33.096140605 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 12 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3332.95it/s]
[W807 01:17:46.100868896 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 13 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3382.16it/s]
[W807 01:17:59.072210790 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 14 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 2718.30it/s]
[W807 01:18:12.003674409 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 15 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4233.40it/s]
[W807 01:18:25.812402079 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 16 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3330.40it/s]
[W807 01:18:38.743675883 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 17 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4055.58it/s]
[W807 01:18:51.694047315 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 18 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3414.93it/s]
[W807 01:19:04.485777825 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 7, run 19 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3442.82it/s]
[W807 01:19:17.382405310 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 0 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4046.48it/s]
[W807 01:19:30.280067196 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 1 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4360.19it/s]
[W807 01:19:43.216823277 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 2 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4712.12it/s]
[W807 01:19:55.010454192 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 3 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4520.98it/s]
[W807 01:20:08.001429188 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 4 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3348.64it/s]
[W807 01:20:21.918878652 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 5 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3556.43it/s]
[W807 01:20:34.670256064 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 6 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4520.24it/s]
[W807 01:20:47.574928471 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 7 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3453.38it/s]
[W807 01:21:00.564245515 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 8 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3403.28it/s]
[W807 01:21:13.347362507 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 9 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4234.03it/s]
[W807 01:21:26.330959906 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 10 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4534.48it/s]
[W807 01:21:39.291350078 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 1248329728, total: 16600465408).

model 8, run 11 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4230.63it/s]
[W807 01:21:52.275818394 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 8, run 12 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4372.08it/s]
[W807 01:22:05.187010303 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 8, run 13 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3511.48it/s]
[W807 01:22:18.157143602 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 8, run 14 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3497.92it/s]
[W807 01:22:30.075653417 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 8, run 15 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4791.34it/s]
[W807 01:22:43.854217146 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 8, run 16 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4288.67it/s]
[W807 01:22:56.759495482 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 8, run 17 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4589.87it/s]
[W807 01:23:09.746205298 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 8, run 18 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3576.30it/s]
[W807 01:23:22.661372256 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 8, run 19 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3466.50it/s]
[W807 01:23:35.266252757 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 0 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3399.77it/s]
[W807 01:23:47.859184857 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 1 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3400.50it/s]
[W807 01:24:00.803617875 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 2 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4457.86it/s]
[W807 01:24:13.528572308 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 3 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4422.75it/s]
[W807 01:24:26.467941303 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 4 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3484.44it/s]
[W807 01:24:39.399622321 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 5 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4375.24it/s]
[W807 01:24:52.161053839 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 6 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4322.29it/s]
[W807 01:25:04.094175688 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 7 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3574.18it/s]
[W807 01:25:17.100182049 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 8 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4278.41it/s]
[W807 01:25:30.988610190 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 9 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4246.33it/s]
[W807 01:25:43.712738224 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 10 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4495.79it/s]
[W807 01:25:56.678161055 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 11 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4303.46it/s]
[W807 01:26:09.586970032 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 12 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3550.27it/s]
[W807 01:26:22.391518998 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 13 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4318.61it/s]
[W807 01:26:35.319083577 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 14 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4505.88it/s]
[W807 01:26:48.257975355 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 933167104, total: 16600465408).

model 9, run 15 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3525.42it/s]
[W807 01:27:01.152020063 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 962527232, total: 16600465408).

model 9, run 16 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3587.72it/s]
[W807 01:27:13.957005882 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 962527232, total: 16600465408).

model 9, run 17 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 4424.31it/s]
[W807 01:27:26.867646217 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 962527232, total: 16600465408).

model 9, run 18 done

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290/290 [00:00<00:00, 3602.19it/s]
[W807 01:27:39.826562774 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 2489319424 bytes (free: 962527232, total: 16600465408).

model 9, run 19 done

In [53]:
# verify
print("Tensor shape:", qwen_logit_tensor.shape)  # expect (10, 20, 2376, 3)
np.save(Path(cfg.output_directory_foundation_nondeterministic) / "logit_tensor_nondeterministic.npy", qwen_logit_tensor)

Tensor shape: (10, 20, 2376, 3)

In [54]:
# same logit comparison as above
for i in range(cfg.n_models):
    within_model_diff = np.max(np.abs(qwen_logit_tensor[i] - qwen_logit_tensor[i, 0]))
    print(f"Max diff within model {i} across 20 runs:", within_model_diff)

for i in range(cfg.n_models):
    between_model_diff = np.max(np.abs(qwen_logit_tensor[0, 0] - qwen_logit_tensor[i, 0]))
    print(f"Max diff between model 0 and model {i} (run 0):", between_model_diff)

Max diff within model 0 across 20 runs: 0.0
Max diff within model 1 across 20 runs: 0.0
Max diff within model 2 across 20 runs: 0.0
Max diff within model 3 across 20 runs: 0.0
Max diff within model 4 across 20 runs: 0.0
Max diff within model 5 across 20 runs: 0.0
Max diff within model 6 across 20 runs: 0.0
Max diff within model 7 across 20 runs: 0.0
Max diff within model 8 across 20 runs: 0.0
Max diff within model 9 across 20 runs: 0.0
Max diff between model 0 and model 0 (run 0): 0.0
Max diff between model 0 and model 1 (run 0): 3.46875
Max diff between model 0 and model 2 (run 0): 3.671875
Max diff between model 0 and model 3 (run 0): 3.109375
Max diff between model 0 and model 4 (run 0): 3.9140625
Max diff between model 0 and model 5 (run 0): 3.296875
Max diff between model 0 and model 6 (run 0): 3.484375
Max diff between model 0 and model 7 (run 0): 3.9375
Max diff between model 0 and model 8 (run 0): 3.46875
Max diff between model 0 and model 9 (run 0): 4.46875